# # sls wsgi serve -p 8000


service: basic
provider:
 name: aws
 runtime: python3.11
 stage: prod
 region: ap-south-1
 memorySize: 128
plugins:
 - serverless-wsgi
 - serverless-python-requirements

custom:
 wsgi:
   app: app.app
   packRequirements: false
functions:
  hello:
    handler: wsgi.handler
    events:
     - http: ANY /
     - http: 'ANY {proxy+}'
    package:
      exclude:
        - node_modules/**
        - venv/**
  person:
    handler: wsgi.handler
    method: GET
    events:
     - http: ANY /
     - http: 'ANY {proxy+}'
    package:
      exclude:
        - node_modules/**
        - venv/**
